#!/bin/sh

USER=$(id -nu 1000)

echo "End on activity on $(date)" >> "/home/logtime.log"
TIMEINIT=$(cat "/home/$USER/.autorun/inittime" | bc)
TIMEEND=$(date +%s)
DELTATIME=$((TIMEEND - TIMEINIT))
H=$(echo "scale=0; $DELTATIME/3600 % 24" | bc)
M=$(echo "scale=0; $DELTATIME/60 % 60" | bc)
S=$(echo "scale=0; $DELTATIME % 60")
echo "Device was active for $H h, $M m, $S s ($DELTATIME s)" >> "/home/logtime.log"
