#!/bin/sh

USER=$(id -nu 1000)
WASACTIVE=$(cat "/usr/share/epitech-log-time/inittime")

if [ "$WASACTIVE" != "" ]; then
    echo "End on activity on $(date)" >> "/usr/share/epitech-log-time/logtime.log"
    TIMEINIT=$(cat "/usr/share/epitech-log-time/inittime" | bc)
    TIMEEND=$(date +%s)
    DELTATIME=$((TIMEEND - TIMEINIT))
    H=$(echo "scale=0; $DELTATIME/3600 % 24" | bc)
    M=$(echo "scale=0; $DELTATIME/60 % 60" | bc)
    S=$(echo "scale=0; $DELTATIME % 60" | bc)
    echo "Device was active for $H h, $M m, $S s ($DELTATIME s)" >> "/usr/share/epitech-log-time/logtime.log"
    echo "" > "/usr/share/epitech-log-time/inittime"
fi
